jQuery.fn.extend({
    wpfclang: function(language){
    	var dictionary = {
    		"All cached files are deleted at the determinated time." : {"tr" : "Belirlenen zamanda önbellekteki tüm dosyalar silinecektir.",
																		 "ru" : "Все файлы в кэш памяти за какое то время удалены.",
																		 "ukr": "всі кешовані файли будуть видалені у встановлений час.",
																		 "es" : "Todos los archivos en el cache serán eliminados a la hora y frecuencia seleccionadas:"},
    		"Choose One" : {"tr" : "Seçin",
    						"ru" : "выбрать один",
    						"ukr": "вибрати один",
    						"es" : "Seleccione"},
    		"Once an hour": {"tr" : "Saatte bir kez",
    						 "ru" : "один раз в час",
    						 "ukr": "один раз на годину",
    						 "es" : "Cada hora"},
    		"Once a day": {"tr" : "Günde bir kez",
    						 "ru" : "один раз в день",
    						 "ukr": "один раз на добу",
    						 "es" : "Una vez al día"},
    		"Twice a day": {"tr" : "Günde iki kez",
    						 "ru" : "дважды в день",
    						 "ukr": "двічі на добу",
    						 "es" : "Dos veces al día"},
    		"Next due": {"tr" : "Sonraki Görev",
						 "ru" : "следующее действие",
						 "ukr": "наступна дія",
						 "es" : "Próximo"},
    		"Schedule": {"tr" : "Vardiya",
						 "ru" : "расписание",
						 "ukr": "розклад",
						 "es" : "Frecuencia"},
			"Server time": {"tr" : "Server tarihi",
						 "ru" : "время сервера",
						 "ukr": "час серверу",
						 "es" : "Hora del servidor"},
    		"You can decrease the size of page" : {"tr" : "Sayfanın boyutunu küçültebilirsiniz",
    											   "ru" : "Вы можете уменьшить размер страницы",
    											   "ukr": "Ви не можете зменшити розмір сторінки",
    											   "es" : "Puede disminuir el tamaño de la página"},
    		"WP Fastest Cache Options": {"tr" : "WP Fastest Cache Seçenekleri",
    									 "ru" : "WP Fastest Cache Опции",
    									 "ukr": "WP Fastest Cache Опції",
    									 "es" : "Opciones de WP Fastest Cache"},									 
    		"Options have been saved" : {"tr" : "Tercihler kaydedildi",
    									 "ru" : "Опции были сохранены",
    									 "ukr": "Опції були збережені",
    									 "es" : "Configuración guardada"},										 
    		".htacces is not writable": {"tr" : ".htacces dosyasının yazma izni yok",
    									 "ru" : ".htacces не может быть записан",
    									 "ukr": ".htacces не може бути записаним",
    									 "es" : "No se puede modificar .htacces"},								 
    		"All cache files have been deleted" : {"tr" : "Önbellekteki tüm dosyalar silindi",
    											   "ru" : "Все файлы кеша были удалены",
    											   "ukr": "Всі файли кеша були видалені",
    											   "es" : "Eliminados todos los archivos en el cache"},						   
			"Language" 				  : {"tr" : "Dil",
										 "ru" : "Язык",
										 "ukr": "Мова",
										 "es" : "Idioma"},
			"Settings"				  : {"tr" : "Ayarlar", 
										 "ru" : "Настройки",
										 "ukr": "Налаштування",
										 "es" : "Configuración"},
			"Delete Cache"            : {"tr" : "Önbellek Temizle", 
										 "ru" : "Удалить Кэш",
										 "ukr": "Видалити Кеш",
										 "es" : "Limpiar cache"}, 
			"Cache Timeout"      	  : {"tr" : "Zaman Aşımı", 
										 "ru" : "Кэш Тайм-аута",
										 "ukr": "Кеш Тайм-ауту", 
										 "es" : "Tiempo de espera del cache"}, 
			"Cache System"            : {"tr" : "Cache Sistemi",
										 "ru" : "Кэш Системы",
										 "ukr": "Кеш Системи",
										 "es" : "Sistema de cache"}, 
			"Enable"                  : {"tr" : "Açık",
										 "ru" : "Включить",
										 "ukr": "Включити",
										 "es" : "Activar"}, 
			"New Post"                : {"tr" : "Yeni Yazı",
										 "ru" : "Новый Пост",
										 "ukr": "Новий Пост",
										 "es" : "Nueva entrada"}, 
			"Clear all cache files when a post or page is published" : {"tr" : "Yeni bir yazı veya sayfa eklenirse tüm önbelleği temizle",
																		"ru" : "Удалить все файлы кэша, когда пост или страница опубликованы",
																		"ukr": "Видалити всі файли кешу, коли пост або сторінка опубліковани",
																		"es" : "Limpiar todo el cache cuando se publiquen una entrada o página nuevas"},
			"Submit"  				  : {"tr" : "Gönder",
										 "ru" : "Отправить",
										 "ukr": "Відправити",
										 "es" : "Enviar"},
			"Delete Now" 			  : {"tr" : "Temizle Şimdi",
										 "ru" : "Удалить Сейчас",
										 "ukr": "Видалити Зараз",
										 "es" : "Eliminar ahora"},
			"You can delete all cache files" : {"tr" : "Tüm önbelleği temizleyebilirsiniz",
												 "ru" : "Вы можете удалить все кэшированные файлы",
												 "ukr": "ви можете видалили всі кешированні файли",
												 "es" : "Puede eliminar todos los archivos en el cache"},
			"Target folder"           : {"tr" : "Hedef klasör",
										 "ru" : "Целевая папка",
										 "ukr": "Цільова папка",
										 "es" : "Carpeta de destino"},
			"It will active in the next version" : {"tr" : "Bir sonraki versiyonda aktif olacaktır",
													"ru" : "Эта функция будет активной в следующей версии",
													"ukr":"Ця функція стане активною в наступній версії",
													"es" :"Activo en la siguiente versión"},
			"You can decrease the size of css files" : {"tr" : "CSS dosyalarının boyununu küçültebilirsiniz",
													"ru" : "вы можете уменьшить размер css файлов",
													"ukr":"ви можете зменшити розмір css файлів",
													"es" :"Puede disminuir el tamaño de los archivos CSS"},
			"Reduce the size of files sent from your server" : {"tr" : "Serverdan gönderilen dosyaların boyutunu küçült",
													"ru" : "уменьшите размер файлов, присланных вашим сервером",
													"ukr":"зменшите розмір файлів, що надійшли від вашого серверу",
													"es" :"Reducir el tamaño de los archivos enviados por el servidor"},
			"Having Issues?" : {"tr" : "Sorun Var Mı?",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"You can create a ticket" : {"tr" : "Destek talebi oluşturabilirsiniz",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"WordPress support forum" : {"tr" : "WordPress destek forumu",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Compacting HTML code, including any inline JavaScript and CSS contained in it, can save many bytes of data and speed up downloading, parsing, and execution time." : {"tr" : "HTML kodu sıkıştırma, datadan birçok veri kazanmayı ve indirmeyi, ayrıştırmayı, çalıştırma süresini  hızlandırır.",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Compacting CSS code can save many bytes of data and speed up downloading, parsing, and execution time." : {"tr" : "CSS kodu sıkıştırma, datadan birçok veri kazanmayı ve indirmeyi, ayrıştırmayı, çalıştırma süresini hızlandırır.",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Enable Gzip Compression" : {"tr" : "Gzip Sıkıştırmayı Aktif Etmek",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Increase page speed" : {"tr" : "Sayfa hızını artırır",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Reduce sizes of pages by up to 70%" : {"tr" : "Sayfanın boyutunun %70'e kadar küçültür",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Reduce the size of files sent from your server to increase the speed to which they are transferred to the browser." : {"tr" : "Server tarafından gönderilen dosyanın boyutunun küçültülmesi, browser tarafından transfer edilirken hızlı transfer edilmesini sağlar. ",
													"ru" : "",
													"ukr":"",
													"es" :""},
			"Cost-benefit ratio: high" : {"tr" : "Maliyet-fayda oranı: Yüksek",
													"ru" : "",
													"ukr":"",
													"es" :""}
		};
		var el = jQuery(this);
    	var text = el.attr("type") == "submit" ? el.val().trim() : el.text().trim();
    	var converted = typeof dictionary[text] == "undefined" ? dictionary[text] : dictionary[text][language];

    	if(typeof converted != "undefined" && converted){
	    	if(el.attr("type") == "submit"){
	    		el.val(converted);
	    	}else{
	    		el.text(converted);
	    	}
    	}
    }
});
var Wpfclang = {
	language : "",
	init: function(language){
		this.language = language;
		this.translate();
		this.setLanguageInputField();
	},
	setLanguageInputField: function(){
		var self = this;
		jQuery("#wpFastestCacheLanguage").val(self.language);
	},
	translate: function(){
		var self = this;
		jQuery('#wpbody-content label, div.question, .questionCon input[type="submit"], #message p, .wrap h2, #nextVerAct, select option, th, .omni_admin_sidebar h3, .omni_admin_sidebar li, #rule-help-tip h4, #rule-help-tip h1, #rule-help-tip label').each(function(){
			jQuery(this).wpfclang(self.language);
		});
	}
}